<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SqlHarness.Core\SqlHarness.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>sqlharness</AssemblyName>
    <RootNamespace>SqlHarness.Cli</RootNamespace>
    <RollForward>Major</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlHarness.Mcp\SqlHarness.Mcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SqlHarness.Dashboard\SqlHarness.Dashboard.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" />
  </ItemGroup>

</Project>
