<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SqlHarness.Tests" />
    <InternalsVisibleTo Include="SqlHarness.Mcp.Tests" />
    <InternalsVisibleTo Include="SqlHarness.Dashboard" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" />
    <PackageReference Include="SQLitePCLRaw.core" />
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" />
    <PackageReference Include="Microsoft.SqlServer.Types" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="SqlParserCS" />
  </ItemGroup>

</Project>
